version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codocodile-nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - codocodile-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: codocodile-backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/local.env
    networks:
      - codocodile-network
    restart: unless-stopped

networks:
  codocodile-network:
    driver: bridge

